# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx1G
org.gradle.parallel = true

# Fabric Properties
	# check these on https://fabricmc.net/develop
	minecraft_version = 26.2
	loader_version = 0.19.3

# Mod Properties
	mod_id = techutils
	mod_name = Technical Utilities
	mod_version = 0.7.1
	modrinth_id = hNoAJSm7

# Publishing
	release_type = release
	repo_owner = kikugie
	maven_group = dev.kikugie
	archives_base_name = techutils

# Fabric Mod Metadata
	minecraft_dependency = ~26.2
	loader_dependency = >=0.17.0

# Build Information
# The target mc versions for the mod during mod publishing
	title_version = 26.2
	release_versions = 26.2

# Dev Dependencies
	loom_version = 1.17.13
	mod_publish_version = 2.1.+

# Dependencies
	fabric_asm_version = 2.3

	fabric_api_version = 0.153.0+26.2

# https://modrinth.com/mod/modmenu/versions
	modmenu_version = 20.0.0-beta.4

# https://masa.dy.fi/maven/sakura-ryoko/fi/dy/masa/malilib/
	malilib_version = 26.2:0.29.3
	malilib_dependency = 0.29.3
	malilib_dependency_modrinth = xKxhjDJ2

# https://masa.dy.fi/maven/sakura-ryoko/fi/dy/masa/litematica/
	litematica_version = 26.2:0.28.3
	litematica_dependency = 0.28.3
	litematica_dependency_modrinth = Yxyi6tlv

# https://masa.dy.fi/maven/sakura-ryoko/fi/dy/masa/tweakeroo/
	tweakeroo_version = 26.2:0.29.2

# https://maven.enginehub.org/repo/com/sk89q/worldedit/
	worldedit_version = 26.2:7.4.4
	breaks_worldedit_dependency = 7.4.4
	worldedit_dependency_modrinth = j2w3GmPv

# https://maven.enginehub.org/repo/org/enginehub/worldeditcui-protocol
	worldeditcui_protocol_version = 26.2:4.0.3
