# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx1G
org.gradle.parallel = true

# Fabric Properties
	# check these on https://fabricmc.net/develop
	minecraft_version = 26.1
	loader_version = 0.19.3

# Mod Properties
	mod_id = techutils
	mod_name = Technical Utilities
	mod_version = 0.7.0
	modrinth_id = hNoAJSm7

# Publishing
	release_type = release
	repo_owner = kikugie
	maven_group = dev.kikugie
	archives_base_name = techutils

# Fabric Mod Metadata
	minecraft_dependency = ~26.1
	loader_dependency = >=0.17.0

# Build Information
# The target mc versions for the mod during mod publishing
	title_version = 26.1
	release_versions = 26.1 26.1.1 26.1.2

# Dev Dependencies
	loom_version = 1.16.3
	mod_publish_version = 2.1.+

# Dependencies
	fabric_asm_version = 2.3

	fabric_api_version = 0.145.4+26.1.1

# https://modrinth.com/mod/modmenu/versions
	modmenu_version = 18.0.0-alpha.8

# https://masa.dy.fi/maven/sakura-ryoko/fi/dy/masa/malilib/
	malilib_version = 26.1.2:0.28.9
	malilib_dependency = 0.28.9
	malilib_dependency_modrinth = xGyGn0t9

# https://masa.dy.fi/maven/sakura-ryoko/fi/dy/masa/litematica/
	litematica_version = 26.1.2:0.27.9
	litematica_dependency = 0.27.9
	litematica_dependency_modrinth = HHOD2rWF

# https://masa.dy.fi/maven/sakura-ryoko/fi/dy/masa/tweakeroo/
	tweakeroo_version = 26.1.2:0.28.6

# https://maven.enginehub.org/repo/com/sk89q/worldedit/
	worldedit_version = 26.1.2:7.4.3
	breaks_worldedit_dependency = 7.4.3
	worldedit_dependency_modrinth = gjsLvJfW

# https://maven.enginehub.org/repo/org/enginehub/worldeditcui-protocol
	worldeditcui_protocol_version = 26.1:4.0.3
