[versions]
minecraft                    = "26.1"
fabric-loader                = { strictly = "0.19.5" }
fabric-api                   = { strictly = "0.154.2+26.1.2" }
fabric-asm                   = "v2.3"
modmenu                      = "18.0.0-alpha.8"
malilib                      = { strictly = "0.28.12" }
litematica                   = "0.27.14"
tweakeroo                    = "0.28.9"
worldedit                    = "7.4.3"
worldeditcui-protocol-common = "4.0.3"
worldeditcui-protocol-fabric = "4.0.3"

# Plugins
fabric-loom = "1.17.20"
mod-publish = "2.2.+"

[libraries]
minecraft     = { module = "com.mojang:minecraft"                           , version.ref = "minecraft"     }
fabric-loader = { module = "net.fabricmc:fabric-loader"                     , version.ref = "fabric-loader" }
fabric-asm    = { module = "com.github.Chocohead:Fabric-ASM"                , version.ref = "fabric-asm"    }
fabric-api    = { module = "net.fabricmc.fabric-api:fabric-api"             , version.ref = "fabric-api"    }
modmenu       = { module = "com.terraformersmc:modmenu"                     , version.ref = "modmenu"       }
malilib       = { module = "fi.dy.masa.malilib:malilib-fabric-26.1.2"       , version.ref = "malilib"       }
litematica    = { module = "fi.dy.masa.litematica:litematica-fabric-26.1.2" , version.ref = "litematica"    }
tweakeroo     = { module = "fi.dy.masa.tweakeroo:tweakeroo-fabric-26.1.2"   , version.ref = "tweakeroo"     }
worldedit     = { module = "com.sk89q.worldedit:worldedit-fabric-mc26.1.2"  , version.ref = "worldedit"     }

[libraries.worldeditcui-protocol-common]
module = "org.enginehub.worldeditcui-protocol:worldeditcui-protocol-common-mc26.1"
version.ref = "worldeditcui-protocol-common"

[libraries.worldeditcui-protocol-fabric]
module = "org.enginehub.worldeditcui-protocol:worldeditcui-protocol-fabric-mc26.1"
version.ref = "worldeditcui-protocol-fabric"

[plugins]
fabric-loom = { id = "net.fabricmc.fabric-loom"       , version.ref = "fabric-loom" }
mod-publish = { id = "me.modmuss50.mod-publish-plugin", version.ref = "mod-publish" }
